//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchInterface) DeepCopyInto(out *BranchInterface) {
	*out = *in
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPv4CIDRs != nil {
		in, out := &in.IPv4CIDRs, &out.IPv4CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPv6CIDRs != nil {
		in, out := &in.IPv6CIDRs, &out.IPv6CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchInterface.
func (in *BranchInterface) DeepCopy() *BranchInterface {
	if in == nil {
		return nil
	}
	out := new(BranchInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINode) DeepCopyInto(out *CNINode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINode.
func (in *CNINode) DeepCopy() *CNINode {
	if in == nil {
		return nil
	}
	out := new(CNINode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNINode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINodeList) DeepCopyInto(out *CNINodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNINode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINodeList.
func (in *CNINodeList) DeepCopy() *CNINodeList {
	if in == nil {
		return nil
	}
	out := new(CNINodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNINodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINodeSpec) DeepCopyInto(out *CNINodeSpec) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]Feature, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINodeSpec.
func (in *CNINodeSpec) DeepCopy() *CNINodeSpec {
	if in == nil {
		return nil
	}
	out := new(CNINodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINodeStatus) DeepCopyInto(out *CNINodeStatus) {
	*out = *in
	if in.TrunkInterface != nil {
		in, out := &in.TrunkInterface, &out.TrunkInterface
		*out = new(TrunkInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeNetworkState != nil {
		in, out := &in.NodeNetworkState, &out.NodeNetworkState
		*out = new(NodeNetworkState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINodeStatus.
func (in *CNINodeStatus) DeepCopy() *CNINodeStatus {
	if in == nil {
		return nil
	}
	out := new(CNINodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTrackingConfig) DeepCopyInto(out *ConnectionTrackingConfig) {
	*out = *in
	if in.TCPEstablishedTimeout != nil {
		in, out := &in.TCPEstablishedTimeout, &out.TCPEstablishedTimeout
		*out = new(int32)
		**out = **in
	}
	if in.UDPStreamTimeout != nil {
		in, out := &in.UDPStreamTimeout, &out.UDPStreamTimeout
		*out = new(int32)
		**out = **in
	}
	if in.UDPTimeout != nil {
		in, out := &in.UDPTimeout, &out.UDPTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTrackingConfig.
func (in *ConnectionTrackingConfig) DeepCopy() *ConnectionTrackingConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionTrackingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Feature) DeepCopyInto(out *Feature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Feature.
func (in *Feature) DeepCopy() *Feature {
	if in == nil {
		return nil
	}
	out := new(Feature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkState) DeepCopyInto(out *NodeNetworkState) {
	*out = *in
	if in.PrimaryNetworkInterfaceSecurityGroups != nil {
		in, out := &in.PrimaryNetworkInterfaceSecurityGroups, &out.PrimaryNetworkInterfaceSecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionTracking != nil {
		in, out := &in.ConnectionTracking, &out.ConnectionTracking
		*out = new(ConnectionTrackingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkState.
func (in *NodeNetworkState) DeepCopy() *NodeNetworkState {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrunkInterface) DeepCopyInto(out *TrunkInterface) {
	*out = *in
	if in.Branches != nil {
		in, out := &in.Branches, &out.Branches
		*out = make([]BranchInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrunkInterface.
func (in *TrunkInterface) DeepCopy() *TrunkInterface {
	if in == nil {
		return nil
	}
	out := new(TrunkInterface)
	in.DeepCopyInto(out)
	return out
}
