//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINode) DeepCopyInto(out *CNINode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINode.
func (in *CNINode) DeepCopy() *CNINode {
	if in == nil {
		return nil
	}
	out := new(CNINode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNINode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINodeList) DeepCopyInto(out *CNINodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNINode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINodeList.
func (in *CNINodeList) DeepCopy() *CNINodeList {
	if in == nil {
		return nil
	}
	out := new(CNINodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNINodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINodeSpec) DeepCopyInto(out *CNINodeSpec) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]Feature, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINodeSpec.
func (in *CNINodeSpec) DeepCopy() *CNINodeSpec {
	if in == nil {
		return nil
	}
	out := new(CNINodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNINodeStatus) DeepCopyInto(out *CNINodeStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	in.Instance.DeepCopyInto(&out.Instance)
	in.TrunkENI.DeepCopyInto(&out.TrunkENI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNINodeStatus.
func (in *CNINodeStatus) DeepCopy() *CNINodeStatus {
	if in == nil {
		return nil
	}
	out := new(CNINodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTrackingStatus) DeepCopyInto(out *ConnectionTrackingStatus) {
	*out = *in
	if in.TCPEstablishedTimeout != nil {
		in, out := &in.TCPEstablishedTimeout, &out.TCPEstablishedTimeout
		*out = new(int32)
		**out = **in
	}
	if in.UDPStreamTimeout != nil {
		in, out := &in.UDPStreamTimeout, &out.UDPStreamTimeout
		*out = new(int32)
		**out = **in
	}
	if in.UDPTimeout != nil {
		in, out := &in.UDPTimeout, &out.UDPTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTrackingStatus.
func (in *ConnectionTrackingStatus) DeepCopy() *ConnectionTrackingStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionTrackingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Feature) DeepCopyInto(out *Feature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Feature.
func (in *Feature) DeepCopy() *Feature {
	if in == nil {
		return nil
	}
	out := new(Feature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	if in.CurrentInstanceSecurityGroups != nil {
		in, out := &in.CurrentInstanceSecurityGroups, &out.CurrentInstanceSecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrimaryNetworkInterfaceSecurityGroups != nil {
		in, out := &in.PrimaryNetworkInterfaceSecurityGroups, &out.PrimaryNetworkInterfaceSecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionTracking != nil {
		in, out := &in.ConnectionTracking, &out.ConnectionTracking
		*out = new(ConnectionTrackingStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrunkENIStatus) DeepCopyInto(out *TrunkENIStatus) {
	*out = *in
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrunkENIStatus.
func (in *TrunkENIStatus) DeepCopy() *TrunkENIStatus {
	if in == nil {
		return nil
	}
	out := new(TrunkENIStatus)
	in.DeepCopyInto(out)
	return out
}
