// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-resource-controller-k8s/pkg/aws/ec2/api/cleanup (interfaces: ResourceCleaner)

// Package mock_cleanup is a generated GoMock package.
package mock_cleanup

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResourceCleaner is a mock of ResourceCleaner interface.
type MockResourceCleaner struct {
	ctrl     *gomock.Controller
	recorder *MockResourceCleanerMockRecorder
}

// MockResourceCleanerMockRecorder is the mock recorder for MockResourceCleaner.
type MockResourceCleanerMockRecorder struct {
	mock *MockResourceCleaner
}

// NewMockResourceCleaner creates a new mock instance.
func NewMockResourceCleaner(ctrl *gomock.Controller) *MockResourceCleaner {
	mock := &MockResourceCleaner{ctrl: ctrl}
	mock.recorder = &MockResourceCleanerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceCleaner) EXPECT() *MockResourceCleanerMockRecorder {
	return m.recorder
}

// DeleteLeakedResources mocks base method.
func (m *MockResourceCleaner) DeleteLeakedResources() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLeakedResources")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLeakedResources indicates an expected call of DeleteLeakedResources.
func (mr *MockResourceCleanerMockRecorder) DeleteLeakedResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLeakedResources", reflect.TypeOf((*MockResourceCleaner)(nil).DeleteLeakedResources))
}
