---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: controller
    app: vpc-resource-controller
spec:
  selector:
    matchLabels:
      control-plane: controller
  replicas: 2
  template:
    metadata:
      labels:
        control-plane: controller
        app: vpc-resource-controller
    spec:
      serviceAccountName: vpc-resource-controller
      containers:
      - command:
        - /controller
        args:
          - --cluster-name=CLUSTER_NAME
          - --role-arn=USER_ROLE_ARN
          - --enable-leader-election
        image: controller:latest
        name: controller
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.3
            memory: 400Mi
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 61779
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 10
      terminationGracePeriodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
