name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup kubebuilder
      run: |
           arch=$(go env GOARCH)
           os=$(go env GOOS)
           curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_${os}_${arch}.tar.gz | tar -xz -C /tmp/
           sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
           export PATH=$PATH:/usr/local/kubebuilder/bin
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Unit Tests
      run: make test
