// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-resource-controller-k8s/pkg/condition (interfaces: Conditions)

// Package mock_condition is a generated GoMock package.
package mock_condition

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConditions is a mock of Conditions interface.
type MockConditions struct {
	ctrl     *gomock.Controller
	recorder *MockConditionsMockRecorder
}

// MockConditionsMockRecorder is the mock recorder for MockConditions.
type MockConditionsMockRecorder struct {
	mock *MockConditions
}

// NewMockConditions creates a new mock instance.
func NewMockConditions(ctrl *gomock.Controller) *MockConditions {
	mock := &MockConditions{ctrl: ctrl}
	mock.recorder = &MockConditionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConditions) EXPECT() *MockConditionsMockRecorder {
	return m.recorder
}

// GetPodDataStoreSyncStatus mocks base method.
func (m *MockConditions) GetPodDataStoreSyncStatus() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodDataStoreSyncStatus")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetPodDataStoreSyncStatus indicates an expected call of GetPodDataStoreSyncStatus.
func (mr *MockConditionsMockRecorder) GetPodDataStoreSyncStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodDataStoreSyncStatus", reflect.TypeOf((*MockConditions)(nil).GetPodDataStoreSyncStatus))
}

// IsOldVPCControllerDeploymentPresent mocks base method.
func (m *MockConditions) IsOldVPCControllerDeploymentPresent() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOldVPCControllerDeploymentPresent")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOldVPCControllerDeploymentPresent indicates an expected call of IsOldVPCControllerDeploymentPresent.
func (mr *MockConditionsMockRecorder) IsOldVPCControllerDeploymentPresent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOldVPCControllerDeploymentPresent", reflect.TypeOf((*MockConditions)(nil).IsOldVPCControllerDeploymentPresent))
}

// IsPodENIDualStackEnabled mocks base method.
func (m *MockConditions) IsPodENIDualStackEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPodENIDualStackEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPodENIDualStackEnabled indicates an expected call of IsPodENIDualStackEnabled.
func (mr *MockConditionsMockRecorder) IsPodENIDualStackEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPodENIDualStackEnabled", reflect.TypeOf((*MockConditions)(nil).IsPodENIDualStackEnabled))
}

// IsWindowsIPAMEnabled mocks base method.
func (m *MockConditions) IsWindowsIPAMEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWindowsIPAMEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWindowsIPAMEnabled indicates an expected call of IsWindowsIPAMEnabled.
func (mr *MockConditionsMockRecorder) IsWindowsIPAMEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWindowsIPAMEnabled", reflect.TypeOf((*MockConditions)(nil).IsWindowsIPAMEnabled))
}

// IsWindowsPrefixDelegationEnabled mocks base method.
func (m *MockConditions) IsWindowsPrefixDelegationEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWindowsPrefixDelegationEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWindowsPrefixDelegationEnabled indicates an expected call of IsWindowsPrefixDelegationEnabled.
func (mr *MockConditionsMockRecorder) IsWindowsPrefixDelegationEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWindowsPrefixDelegationEnabled", reflect.TypeOf((*MockConditions)(nil).IsWindowsPrefixDelegationEnabled))
}

// SetPodDataStoreSyncStatus mocks base method.
func (m *MockConditions) SetPodDataStoreSyncStatus(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPodDataStoreSyncStatus", arg0)
}

// SetPodDataStoreSyncStatus indicates an expected call of SetPodDataStoreSyncStatus.
func (mr *MockConditionsMockRecorder) SetPodDataStoreSyncStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPodDataStoreSyncStatus", reflect.TypeOf((*MockConditions)(nil).SetPodDataStoreSyncStatus), arg0)
}
